### ISSUE TITLE
customize your blog's README

### ISSUE THREAD

**Issue by ajschumacher** [LucDemortier/LucDemortier.github.io#1]
:earth_asia:

**Comment by ajschumacher** [comment]
HI @LucDemortier! Do you get notifications for github issues like this one?

**Comment by LucDemortier** [comment]
Hi Aaron!

Yes I did get that notification, thank you.  It’s on my to-do list…

Luc

**Comment by ajschumacher** [comment]
Cool! Thanks for the info. :elephant:
